use super::CompilerError;
use crate::{Error, Memory};
use std::collections::BTreeMap;

/// Class files generated by an in-memory compilation.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CompiledClasses(pub(super) BTreeMap<String, Vec<u8>>);

impl CompiledClasses {
    /// Get generated bytecode by binary class name.
    #[must_use]
    pub fn get<S: AsRef<str>>(&self, class_name: S) -> Option<&[u8]> {
        self.0.get(class_name.as_ref()).map(Vec::as_slice)
    }

    /// Iterate over generated classes in binary-name order.
    #[must_use]
    pub fn iter(&self) -> impl ExactSizeIterator<Item = (&str, &[u8])> {
        self.0
            .iter()
            .map(|(class_name, bytecode)| (class_name.as_str(), bytecode.as_slice()))
    }

    /// Return the number of generated classes.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Return whether no classes were generated.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Consume the collection and return its underlying ordered map.
    #[must_use]
    pub fn into_inner(self) -> BTreeMap<String, Vec<u8>> {
        self.0
    }

    /// Add every generated class to an in-memory class path entry.
    ///
    /// # Errors
    ///
    /// if any generated value is not a valid class file
    pub async fn load_into(&self, memory: &Memory) -> Result<(), CompilerError> {
        for bytecode in self.0.values() {
            memory.add_class(bytecode).await.map_err(Error::from)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compiled_classes_are_deterministic() {
        let classes = CompiledClasses(BTreeMap::from([
            ("z.Z".to_string(), vec![2]),
            ("a.A".to_string(), vec![1]),
        ]));
        let names = classes.iter().map(|(name, _)| name).collect::<Vec<_>>();
        assert_eq!(["a.A", "z.Z"], names.as_slice());
        assert_eq!(Some([1].as_slice()), classes.get("a.A"));
        assert_eq!(2, classes.len());
        assert!(!classes.is_empty());
    }
}
