mod java_io_filedescriptor;
mod java_io_fileinputstream;
mod java_io_fileoutputstream;
mod java_io_unixfilesystem;
mod java_lang_class;
mod java_lang_classloader;
mod java_lang_double;
mod java_lang_float;
mod java_lang_object;
mod java_lang_ref_reference;
mod java_lang_runtime;
mod java_lang_shutdown;
mod java_lang_stacktraceelement;
mod java_lang_system;
mod java_lang_thread;
mod java_lang_throwable;
mod jdk_internal_loader_bootloader;
mod jdk_internal_loader_nativelibraries;
mod jdk_internal_misc_cds;
mod jdk_internal_misc_scopedmemoryaccess;
mod jdk_internal_misc_signal;
mod jdk_internal_misc_unsafe;
mod jdk_internal_misc_vm;
mod jdk_internal_reflect_reflection;
mod jdk_internal_util_systemprops_raw;
pub(crate) mod properties;
mod registry;
mod sun_io_win32errormode;

pub use registry::registry;
