#[cfg(target_os = "macos")]
pub mod bsdfilesystem;
#[cfg(target_os = "macos")]
pub mod bsdnativedispatcher;
pub(crate) mod common;
#[cfg(target_os = "linux")]
pub mod gnomefiletypedetector;
#[cfg(target_os = "linux")]
pub mod linuxnativedispatcher;
#[cfg(target_os = "linux")]
pub mod linuxwatchservice;
#[cfg(target_os = "macos")]
pub mod macosxnativedispatcher;
#[cfg(target_os = "linux")]
pub mod magicfiletypedetector;
pub(crate) mod managed_files;
#[cfg(target_os = "windows")]
pub mod registryfiletypedetector;
#[cfg(target_family = "unix")]
pub mod unixcopyfile;
#[cfg(target_family = "unix")]
pub mod unixfilesystem;
pub mod unixnativedispatcher;
#[cfg(target_os = "macos")]
pub mod utifiletypedetector;
#[cfg(target_os = "windows")]
pub mod windowsnativedispatcher;
