pub mod bsdfilesystem;
pub mod bsdnativedispatcher;
#[cfg(target_os = "macos")]
pub mod macosxnativedispatcher;
pub(crate) mod managed_files;
pub mod unixcopyfile;
pub mod unixfilesystem;
pub mod unixnativedispatcher;
pub mod utifiletypedetector;
#[cfg(target_os = "windows")]
pub mod windowsnativedispatcher;
