[package]
edition.workspace = true
name = "class_loader"
publish = false
license.workspace = true
version.workspace = true

[dependencies]
ristretto_classloader = { path = "../../ristretto_classloader" }
